In [1]:
from __future__ import print_function

import torch
print("Torch library imported")

Torch library imported


<h3>
</br>
float a; // This is called a scalar </br></br>

float a[]; // This is called a vector </br>

float a[][]; // This is called a matrix </br>

float a[][][]; // This is a 3D tensor </br>

float a[][][]… n-times … []; // This is an n-D tensor </br>
</h3>

In [2]:
## Basically empty matrix have values that are avaliable in the memory system
## This is also known as uninitalized matrix
x = torch.empty(3,3)
print(x)

tensor([[4.3605e+27, 2.5226e-18, 8.2231e+32],
        [1.8394e+25, 6.1963e-04, 1.0140e-08],
        [2.4796e-12, 2.4754e-12, 7.8447e+17]])


In [3]:
## randomly initalize matrix 

x = torch.rand(3,3)
print(x)

tensor([[0.1259, 0.1788, 0.4713],
        [0.6061, 0.4046, 0.6296],
        [0.6797, 0.7905, 0.3022]])


In [8]:
## construct matrix with data type : float and initalize ZERO's
x = torch.zeros(3,3,dtype=torch.float)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
## creating tensor directly from data

## 3x3 tensor
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [15]:
## taking input from one tensor and forwarding it to another

x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]],dtype=torch.long)
print(x)

y = torch.randn_like(x,dtype= torch.float)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[-0.8072, -0.6608, -0.6356],
        [ 0.0962, -1.0620, -0.0370],
        [ 1.0109,  1.0991,  0.5939]])


In [16]:
## size of tensor 
x.size()

torch.Size([3, 3])

In [21]:
## Operations 

## add
x = torch.rand(3,3)
y = torch.rand(3,3)
print("Addition")
add = (x+y)
print(add)

## Subtraction
print("Subtraction")
sub = (x-y)
print(sub)

## Multiplication
print("Multiplication")
mult = (x*y)
print(mult)


Addition
tensor([[1.6619, 0.6473, 0.7817],
        [1.3700, 1.7865, 1.2841],
        [0.3592, 0.9498, 1.1640]])
Subtraction
tensor([[ 0.2093,  0.3376, -0.7387],
        [ 0.4275, -0.1068,  0.2746],
        [-0.1136,  0.1218, -0.6699]])
Multiplication
tensor([[0.6795, 0.0763, 0.0163],
        [0.4235, 0.7951, 0.3934],
        [0.0290, 0.2218, 0.2266]])


In [30]:
## Resizing tensors

x = torch.rand(3,3,dtype=torch.float)
print(x)
print(x.size())
## view function is use to resize the tensor

## 9 row 1 col
y = x.view(9,1)

## 1 row 9 col
z = x.view(1,9)


## 1 column
zz = x.view(9)

print(y)
print(y.size())
print(z)
print(z.size())
print(zz)
print(zz.size())

tensor([[0.8754, 0.4031, 0.1401],
        [0.0424, 0.2539, 0.2214],
        [0.1493, 0.2215, 0.2589]])
torch.Size([3, 3])
tensor([[0.8754],
        [0.4031],
        [0.1401],
        [0.0424],
        [0.2539],
        [0.2214],
        [0.1493],
        [0.2215],
        [0.2589]])
torch.Size([9, 1])
tensor([[0.8754, 0.4031, 0.1401, 0.0424, 0.2539, 0.2214, 0.1493, 0.2215, 0.2589]])
torch.Size([1, 9])
tensor([0.8754, 0.4031, 0.1401, 0.0424, 0.2539, 0.2214, 0.1493, 0.2215, 0.2589])
torch.Size([9])


In [32]:
## To get value as python number
## THIS ONLY WORKS FOR ONE ELEMENT
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6254])
0.6253655552864075


In [34]:
## tensor to numpy 
x = torch.ones(2,2)
print(x)

y = x.numpy()
print(y)

tensor([[1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]]


In [42]:
## numpy to tensor
import numpy as np
x = np.ones([2,2],dtype=float)
print(x)

y = torch.from_numpy(x)
print(y)

[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [46]:
## CUDA TENSORS

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(2,2,device=device)
    print(x)
    y = x.to(device) # or "cuda"
    print(y)
    z = x+y
    print(z)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[2., 2.],
        [2., 2.]], device='cuda:0')
